### ISSUE TITLE
Readme + license ?

### ISSUE THREAD

**Issue by sadortun** [DemacMedia/ErpBundle#1]
Hi @rodolfobandeira 

Would you be able to add a license and readme file to your bundle?

It would be nice to have more details on what the bundle achieve and what you plan to do.

Thanks,
Samuel

**Comment by rodolfobandeira** [comment]
Hi @sadortun 

It's under OSL. Since it's a very specific bundle, the idea is not to share the project but getting some resources to other developers based on.

Thanks!
